import { Inter } from "@next/font/google";
import "./globals.css";
import "./reset.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Mamiflix",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className="bg-black ">
        <Header></Header>
        <main>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
